name: hello-world-ci

on:
  push:
    paths:
      - 'submissions/hello_world/**'
  pull_request:
    branches:
      - main

jobs:
  run_hello_world:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./submissions/hello_world
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run locally
        run: ./HelloWorld.py
